version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      time: "06:00"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: weekly
      time: "06:00"

  - package-ecosystem: "npm"
    directory: "/ui"
    schedule:
      interval: weekly
      time: "06:00"