# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: "LLM Config Optimizer"
description: "AI-powered Home Assistant configuration analysis and optimization using multiple LLM providers"
version: "0.2.6"
slug: "llm-config-optimizer"
url: "https://github.com/rickoslyder/ha-config-optimizer"

# Supported architectures
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386

# Startup configuration
startup: application
boot: auto
init: false

# Ingress configuration for seamless HA integration
ingress: true
ingress_port: 8099
panel_icon: "mdi:robot-outline"
panel_title: "Config Optimizer"

# Home Assistant API access
homeassistant_api: true
hassio_api: true

# File system access
map:
  - homeassistant_config:rw
  - backup:rw
  - addon_config:rw

# Security
apparmor: true

# Default options
options:
  log_level: "info"
  auto_backup: true
  max_file_size_mb: 10

# Options schema validation
schema:
  log_level: "list(trace|debug|info|notice|warning|error|fatal)?"
  auto_backup: "bool"
  max_file_size_mb: "int(1,100)"

# Docker image (commented out for local development, will be uncommented for releases)
# image: "ghcr.io/rickoslyder/ha-config-optimizer-{arch}"