- alias: "Morning Lights"
  trigger:
    platform: sun
    event: sunrise
  action:
    service: light.turn_on
    target:
      entity_id: light.living_room
      
- alias: "Sunset Lights"
  trigger:
    platform: sun
    event: sunset
  action:
    service: light.turn_on
    target:
      entity_id: light.porch