# Test Home Assistant Configuration
homeassistant:
  name: Test Home
  latitude: 32.8796
  longitude: -96.7070
  elevation: 213
  unit_system: imperial
  time_zone: America/Chicago

# Enable default integrations
default_config:

# Text to speech
tts:
  - platform: google_translate

# Automation example
automation:
  - alias: "Test Automation"
    trigger:
      platform: time
      at: "07:00:00"
    action:
      service: light.turn_on
      target:
        entity_id: light.bedroom

# Example sensors
sensor:
  - platform: template
    sensors:
      test_sensor:
        friendly_name: "Test Sensor"
        value_template: "{{ states('sensor.temperature') | float + 1 }}"